# The URL the site will be built for
base_url = "https://rust-edu.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "Rust Edu"
description = ""

minify_html = false

[extra]

navbar = [
  { url = "/", name = "Home" },
  # { url = "/about", name = "About" },
  { url = "/news", name = "News" },
  { url = "/resources", name = "Resources" },
]